---
title: "[Advent of Code 2020 - Day 6](https://adventofcode.com/2020/day/6)"
author: "parmsam"
date: "12/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(stringr)

setwd("/Users/samparmar/Documents/programming/advent of code/aoc-2020")
```
## Part A
### QUESTION: For each group, count the number of questions to which anyone answered "yes". What is the sum of those counts?
```{r}
a <- readr::read_file("day6input.txt")
b <- str_split(a,"\\n\\n")
c <- data.frame(b) %>% rename("from" = 1) 

c <- c %>% 
  mutate(unique_group_ques = map(from, pattern=letters, str_count)) %>% 
  mutate(unique_group_ques = map(unique_group_ques, as.logical)) %>%
  mutate(unique_group_ques = as.numeric(map(unique_group_ques, sum)))

c %>% summarize(count_uniq_grp_q = sum(unique_group_ques))

```
### ANSWER: 6782

## Part B
### QUESTION: For each group, count the number of questions to which everyone answered "yes". What is the sum of those counts?
```{r}
d <- c %>% mutate(value = strsplit(from, regex(" |\\n"))) %>%
  mutate(group_size = map(value, length) ) %>% 
  select(-value) %>% 
  unnest(cols = c(group_size)) %>%
  mutate(everyone_yes = map(from, pattern=letters, str_count))

yes_letters <- function(vector, size) {
  letters[vector %in% size]
}

# yes_letters(c(0, 1, 5, 0, 1, 0, 0, 0, 0, 0, 1, 5, 0, 5, 0, 5, 0, 0, 0, 0, 5, 0, 0, 1, 0, 5), 5)
# yes_letters(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0), 2)
# yes_letters(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2), 4)

e <- d %>% mutate(everyone_yes_subset = map2(everyone_yes, group_size, yes_letters)) %>% 
  mutate(everyone_yes_ct = as.numeric(map(everyone_yes_subset, length)))
e %>% summarize(sum(everyone_yes_ct))
```
### ANSWER: 3596



